// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package otpgo_trading_backend

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Context struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Dob                  string   `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Context) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Context) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Context) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Context) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *Context) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Context) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Context) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResponseStatus struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetTickerRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Pricing              string   `protobuf:"bytes,2,opt,name=pricing,proto3" json:"pricing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTickerRequest) Reset()         { *m = GetTickerRequest{} }
func (m *GetTickerRequest) String() string { return proto.CompactTextString(m) }
func (*GetTickerRequest) ProtoMessage()    {}
func (*GetTickerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{2}
}

func (m *GetTickerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTickerRequest.Unmarshal(m, b)
}
func (m *GetTickerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTickerRequest.Marshal(b, m, deterministic)
}
func (m *GetTickerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTickerRequest.Merge(m, src)
}
func (m *GetTickerRequest) XXX_Size() int {
	return xxx_messageInfo_GetTickerRequest.Size(m)
}
func (m *GetTickerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTickerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTickerRequest proto.InternalMessageInfo

func (m *GetTickerRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetTickerRequest) GetPricing() string {
	if m != nil {
		return m.Pricing
	}
	return ""
}

type GetTickerResponse struct {
	Last                 int32                `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	High                 int32                `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	Low                  int32                `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Volume               int32                `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	TimeOpen             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time_open,json=timeOpen,proto3" json:"time_open,omitempty"`
	TimeClose            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=time_close,json=timeClose,proto3" json:"time_close,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetTickerResponse) Reset()         { *m = GetTickerResponse{} }
func (m *GetTickerResponse) String() string { return proto.CompactTextString(m) }
func (*GetTickerResponse) ProtoMessage()    {}
func (*GetTickerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{3}
}

func (m *GetTickerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTickerResponse.Unmarshal(m, b)
}
func (m *GetTickerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTickerResponse.Marshal(b, m, deterministic)
}
func (m *GetTickerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTickerResponse.Merge(m, src)
}
func (m *GetTickerResponse) XXX_Size() int {
	return xxx_messageInfo_GetTickerResponse.Size(m)
}
func (m *GetTickerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTickerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTickerResponse proto.InternalMessageInfo

func (m *GetTickerResponse) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *GetTickerResponse) GetHigh() int32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *GetTickerResponse) GetLow() int32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *GetTickerResponse) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *GetTickerResponse) GetTimeOpen() *timestamp.Timestamp {
	if m != nil {
		return m.TimeOpen
	}
	return nil
}

func (m *GetTickerResponse) GetTimeClose() *timestamp.Timestamp {
	if m != nil {
		return m.TimeClose
	}
	return nil
}

type GetOrderBookRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Pricing              string   `protobuf:"bytes,2,opt,name=pricing,proto3" json:"pricing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderBookRequest) Reset()         { *m = GetOrderBookRequest{} }
func (m *GetOrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderBookRequest) ProtoMessage()    {}
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{4}
}

func (m *GetOrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderBookRequest.Unmarshal(m, b)
}
func (m *GetOrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderBookRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderBookRequest.Merge(m, src)
}
func (m *GetOrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderBookRequest.Size(m)
}
func (m *GetOrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderBookRequest proto.InternalMessageInfo

func (m *GetOrderBookRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetOrderBookRequest) GetPricing() string {
	if m != nil {
		return m.Pricing
	}
	return ""
}

type OrderBookEntry struct {
	Price                int32    `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookEntry) Reset()         { *m = OrderBookEntry{} }
func (m *OrderBookEntry) String() string { return proto.CompactTextString(m) }
func (*OrderBookEntry) ProtoMessage()    {}
func (*OrderBookEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{5}
}

func (m *OrderBookEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookEntry.Unmarshal(m, b)
}
func (m *OrderBookEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookEntry.Marshal(b, m, deterministic)
}
func (m *OrderBookEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookEntry.Merge(m, src)
}
func (m *OrderBookEntry) XXX_Size() int {
	return xxx_messageInfo_OrderBookEntry.Size(m)
}
func (m *OrderBookEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookEntry proto.InternalMessageInfo

func (m *OrderBookEntry) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderBookEntry) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderBookEntry) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetOrderBookResponse struct {
	Asks                 []*OrderBookEntry `protobuf:"bytes,1,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*OrderBookEntry `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetOrderBookResponse) Reset()         { *m = GetOrderBookResponse{} }
func (m *GetOrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderBookResponse) ProtoMessage()    {}
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{6}
}

func (m *GetOrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderBookResponse.Unmarshal(m, b)
}
func (m *GetOrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderBookResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderBookResponse.Merge(m, src)
}
func (m *GetOrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderBookResponse.Size(m)
}
func (m *GetOrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderBookResponse proto.InternalMessageInfo

func (m *GetOrderBookResponse) GetAsks() []*OrderBookEntry {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *GetOrderBookResponse) GetBids() []*OrderBookEntry {
	if m != nil {
		return m.Bids
	}
	return nil
}

type GetBalanceRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type GetBalanceResponse struct {
	Balance              int32    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Decimalplaces        int32    `protobuf:"varint,2,opt,name=decimalplaces,proto3" json:"decimalplaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8}
}

func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(m, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetBalanceResponse) GetDecimalplaces() int32 {
	if m != nil {
		return m.Decimalplaces
	}
	return 0
}

type GetOpenOrdersRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOpenOrdersRequest) Reset()         { *m = GetOpenOrdersRequest{} }
func (m *GetOpenOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetOpenOrdersRequest) ProtoMessage()    {}
func (*GetOpenOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9}
}

func (m *GetOpenOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOpenOrdersRequest.Unmarshal(m, b)
}
func (m *GetOpenOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOpenOrdersRequest.Marshal(b, m, deterministic)
}
func (m *GetOpenOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOpenOrdersRequest.Merge(m, src)
}
func (m *GetOpenOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetOpenOrdersRequest.Size(m)
}
func (m *GetOpenOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOpenOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOpenOrdersRequest proto.InternalMessageInfo

func (m *GetOpenOrdersRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type OpenOrderEntry struct {
	Id                      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency                string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Pricing                 string   `protobuf:"bytes,3,opt,name=pricing,proto3" json:"pricing,omitempty"`
	AmountCurrency          int32    `protobuf:"varint,4,opt,name=amount_currency,json=amountCurrency,proto3" json:"amount_currency,omitempty"`
	AmountCurrencyRemaining int32    `protobuf:"varint,5,opt,name=amount_currency_remaining,json=amountCurrencyRemaining,proto3" json:"amount_currency_remaining,omitempty"`
	AmountPricing           int32    `protobuf:"varint,6,opt,name=amount_pricing,json=amountPricing,proto3" json:"amount_pricing,omitempty"`
	AmountPricingRemaining  int32    `protobuf:"varint,7,opt,name=amount_pricing_remaining,json=amountPricingRemaining,proto3" json:"amount_pricing_remaining,omitempty"`
	PriceBid                int32    `protobuf:"varint,8,opt,name=price_bid,json=priceBid,proto3" json:"price_bid,omitempty"`
	PriceAsk                int32    `protobuf:"varint,9,opt,name=price_ask,json=priceAsk,proto3" json:"price_ask,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *OpenOrderEntry) Reset()         { *m = OpenOrderEntry{} }
func (m *OpenOrderEntry) String() string { return proto.CompactTextString(m) }
func (*OpenOrderEntry) ProtoMessage()    {}
func (*OpenOrderEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{10}
}

func (m *OpenOrderEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenOrderEntry.Unmarshal(m, b)
}
func (m *OpenOrderEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenOrderEntry.Marshal(b, m, deterministic)
}
func (m *OpenOrderEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenOrderEntry.Merge(m, src)
}
func (m *OpenOrderEntry) XXX_Size() int {
	return xxx_messageInfo_OpenOrderEntry.Size(m)
}
func (m *OpenOrderEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenOrderEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OpenOrderEntry proto.InternalMessageInfo

func (m *OpenOrderEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenOrderEntry) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *OpenOrderEntry) GetPricing() string {
	if m != nil {
		return m.Pricing
	}
	return ""
}

func (m *OpenOrderEntry) GetAmountCurrency() int32 {
	if m != nil {
		return m.AmountCurrency
	}
	return 0
}

func (m *OpenOrderEntry) GetAmountCurrencyRemaining() int32 {
	if m != nil {
		return m.AmountCurrencyRemaining
	}
	return 0
}

func (m *OpenOrderEntry) GetAmountPricing() int32 {
	if m != nil {
		return m.AmountPricing
	}
	return 0
}

func (m *OpenOrderEntry) GetAmountPricingRemaining() int32 {
	if m != nil {
		return m.AmountPricingRemaining
	}
	return 0
}

func (m *OpenOrderEntry) GetPriceBid() int32 {
	if m != nil {
		return m.PriceBid
	}
	return 0
}

func (m *OpenOrderEntry) GetPriceAsk() int32 {
	if m != nil {
		return m.PriceAsk
	}
	return 0
}

type GetOpenOrdersResponse struct {
	Openorders           []*OpenOrderEntry `protobuf:"bytes,1,rep,name=openorders,proto3" json:"openorders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetOpenOrdersResponse) Reset()         { *m = GetOpenOrdersResponse{} }
func (m *GetOpenOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOpenOrdersResponse) ProtoMessage()    {}
func (*GetOpenOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{11}
}

func (m *GetOpenOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOpenOrdersResponse.Unmarshal(m, b)
}
func (m *GetOpenOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOpenOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetOpenOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOpenOrdersResponse.Merge(m, src)
}
func (m *GetOpenOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOpenOrdersResponse.Size(m)
}
func (m *GetOpenOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOpenOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOpenOrdersResponse proto.InternalMessageInfo

func (m *GetOpenOrdersResponse) GetOpenorders() []*OpenOrderEntry {
	if m != nil {
		return m.Openorders
	}
	return nil
}

type CancelOrderRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{12}
}

func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(m, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type PlaceOrderRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Pricing              string   `protobuf:"bytes,2,opt,name=pricing,proto3" json:"pricing,omitempty"`
	AmountCurrency       int32    `protobuf:"varint,3,opt,name=amount_currency,json=amountCurrency,proto3" json:"amount_currency,omitempty"`
	AmountPricing        int32    `protobuf:"varint,4,opt,name=amount_pricing,json=amountPricing,proto3" json:"amount_pricing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{13}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PlaceOrderRequest) GetPricing() string {
	if m != nil {
		return m.Pricing
	}
	return ""
}

func (m *PlaceOrderRequest) GetAmountCurrency() int32 {
	if m != nil {
		return m.AmountCurrency
	}
	return 0
}

func (m *PlaceOrderRequest) GetAmountPricing() int32 {
	if m != nil {
		return m.AmountPricing
	}
	return 0
}

type GetTransactionHistoryRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionHistoryRequest) Reset()         { *m = GetTransactionHistoryRequest{} }
func (m *GetTransactionHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionHistoryRequest) ProtoMessage()    {}
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{14}
}

func (m *GetTransactionHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionHistoryRequest.Unmarshal(m, b)
}
func (m *GetTransactionHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionHistoryRequest.Merge(m, src)
}
func (m *GetTransactionHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionHistoryRequest.Size(m)
}
func (m *GetTransactionHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionHistoryRequest proto.InternalMessageInfo

func (m *GetTransactionHistoryRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Transaction struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Currency             string               `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               int32                `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Note                 string               `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{15}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Transaction) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Transaction) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type GetTransactionHistoryResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionHistoryResponse) Reset()         { *m = GetTransactionHistoryResponse{} }
func (m *GetTransactionHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionHistoryResponse) ProtoMessage()    {}
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{16}
}

func (m *GetTransactionHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionHistoryResponse.Unmarshal(m, b)
}
func (m *GetTransactionHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionHistoryResponse.Merge(m, src)
}
func (m *GetTransactionHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionHistoryResponse.Size(m)
}
func (m *GetTransactionHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionHistoryResponse proto.InternalMessageInfo

func (m *GetTransactionHistoryResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetHistoryRequest struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Pricing              string   `protobuf:"bytes,2,opt,name=pricing,proto3" json:"pricing,omitempty"`
	Interval             int32    `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryRequest) Reset()         { *m = GetHistoryRequest{} }
func (m *GetHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetHistoryRequest) ProtoMessage()    {}
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{17}
}

func (m *GetHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryRequest.Unmarshal(m, b)
}
func (m *GetHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryRequest.Merge(m, src)
}
func (m *GetHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetHistoryRequest.Size(m)
}
func (m *GetHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryRequest proto.InternalMessageInfo

func (m *GetHistoryRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetHistoryRequest) GetPricing() string {
	if m != nil {
		return m.Pricing
	}
	return ""
}

func (m *GetHistoryRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type GetHistoryResponse struct {
	Volume               int32    `protobuf:"varint,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp            int32    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Low                  int32    `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	High                 int32    `protobuf:"varint,4,opt,name=high,proto3" json:"high,omitempty"`
	Open                 int32    `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	Close                int32    `protobuf:"varint,6,opt,name=close,proto3" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryResponse) Reset()         { *m = GetHistoryResponse{} }
func (m *GetHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetHistoryResponse) ProtoMessage()    {}
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{18}
}

func (m *GetHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryResponse.Unmarshal(m, b)
}
func (m *GetHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryResponse.Merge(m, src)
}
func (m *GetHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetHistoryResponse.Size(m)
}
func (m *GetHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryResponse proto.InternalMessageInfo

func (m *GetHistoryResponse) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *GetHistoryResponse) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetHistoryResponse) GetLow() int32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *GetHistoryResponse) GetHigh() int32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *GetHistoryResponse) GetOpen() int32 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *GetHistoryResponse) GetClose() int32 {
	if m != nil {
		return m.Close
	}
	return 0
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{19}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{20}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetProfileRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{21}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Context)(nil), "otpgo.trading.backend.Context")
	proto.RegisterType((*ResponseStatus)(nil), "otpgo.trading.backend.ResponseStatus")
	proto.RegisterType((*GetTickerRequest)(nil), "otpgo.trading.backend.GetTickerRequest")
	proto.RegisterType((*GetTickerResponse)(nil), "otpgo.trading.backend.GetTickerResponse")
	proto.RegisterType((*GetOrderBookRequest)(nil), "otpgo.trading.backend.GetOrderBookRequest")
	proto.RegisterType((*OrderBookEntry)(nil), "otpgo.trading.backend.OrderBookEntry")
	proto.RegisterType((*GetOrderBookResponse)(nil), "otpgo.trading.backend.GetOrderBookResponse")
	proto.RegisterType((*GetBalanceRequest)(nil), "otpgo.trading.backend.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "otpgo.trading.backend.GetBalanceResponse")
	proto.RegisterType((*GetOpenOrdersRequest)(nil), "otpgo.trading.backend.GetOpenOrdersRequest")
	proto.RegisterType((*OpenOrderEntry)(nil), "otpgo.trading.backend.OpenOrderEntry")
	proto.RegisterType((*GetOpenOrdersResponse)(nil), "otpgo.trading.backend.GetOpenOrdersResponse")
	proto.RegisterType((*CancelOrderRequest)(nil), "otpgo.trading.backend.CancelOrderRequest")
	proto.RegisterType((*PlaceOrderRequest)(nil), "otpgo.trading.backend.PlaceOrderRequest")
	proto.RegisterType((*GetTransactionHistoryRequest)(nil), "otpgo.trading.backend.GetTransactionHistoryRequest")
	proto.RegisterType((*Transaction)(nil), "otpgo.trading.backend.Transaction")
	proto.RegisterType((*GetTransactionHistoryResponse)(nil), "otpgo.trading.backend.GetTransactionHistoryResponse")
	proto.RegisterType((*GetHistoryRequest)(nil), "otpgo.trading.backend.GetHistoryRequest")
	proto.RegisterType((*GetHistoryResponse)(nil), "otpgo.trading.backend.GetHistoryResponse")
	proto.RegisterType((*LoginRequest)(nil), "otpgo.trading.backend.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "otpgo.trading.backend.LogoutRequest")
	proto.RegisterType((*GetProfileRequest)(nil), "otpgo.trading.backend.GetProfileRequest")
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5) }

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 1120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6f, 0xdc, 0x44,
	0x10, 0xaf, 0xef, 0xce, 0x97, 0xbb, 0xc9, 0x07, 0xed, 0xd2, 0x16, 0x63, 0x02, 0x54, 0x4b, 0xa2,
	0x26, 0x80, 0x2e, 0x52, 0x8a, 0x44, 0xdb, 0x37, 0x12, 0x95, 0x54, 0xa2, 0x52, 0x82, 0x9b, 0x0a,
	0x9e, 0x38, 0x7c, 0xf6, 0xc6, 0x59, 0x9d, 0x6f, 0xd7, 0xd8, 0x7b, 0x81, 0xbc, 0xf3, 0x88, 0xc4,
	0x13, 0x0f, 0xf0, 0x3f, 0xf1, 0x8a, 0xc4, 0x7f, 0x83, 0xf6, 0xc3, 0x5f, 0x97, 0xf8, 0xe2, 0x00,
	0x6f, 0x3b, 0xb3, 0xf3, 0x9b, 0x9d, 0x9d, 0xdf, 0xee, 0xcc, 0xc0, 0xfa, 0xc4, 0x0f, 0xa6, 0x84,
	0x85, 0xa3, 0x24, 0xe5, 0x82, 0xa3, 0x07, 0x5c, 0x24, 0x11, 0x1f, 0x89, 0xd4, 0x0f, 0x29, 0x8b,
	0x46, 0x66, 0xd3, 0xfd, 0x30, 0xe2, 0x3c, 0x8a, 0xc9, 0x9e, 0x32, 0x9a, 0xcc, 0xcf, 0xf6, 0x04,
	0x9d, 0x91, 0x4c, 0xf8, 0xb3, 0x44, 0xe3, 0xf0, 0x9f, 0x16, 0xac, 0x1c, 0x72, 0x26, 0xc8, 0x4f,
	0x02, 0xb9, 0x30, 0xb8, 0x20, 0x29, 0x3d, 0xa3, 0x24, 0x74, 0xac, 0x47, 0xd6, 0xce, 0xc0, 0x2b,
	0x64, 0xb4, 0x09, 0xc3, 0x33, 0x9a, 0x66, 0x82, 0xf9, 0x33, 0xe2, 0x74, 0x1e, 0x59, 0x3b, 0x43,
	0xaf, 0x54, 0x48, 0x64, 0xec, 0x9b, 0xcd, 0xae, 0xda, 0x2c, 0x64, 0xe4, 0xc0, 0x8a, 0x1f, 0x86,
	0x29, 0xc9, 0x32, 0xa7, 0xa7, 0xb6, 0x72, 0x11, 0xdd, 0x85, 0x6e, 0xc8, 0x27, 0x8e, 0xad, 0xb4,
	0x72, 0x89, 0xee, 0x83, 0x9d, 0x9c, 0x73, 0x46, 0x9c, 0xbe, 0xd2, 0x69, 0x41, 0x6a, 0xc9, 0xcc,
	0xa7, 0xb1, 0xb3, 0xa2, 0xb5, 0x4a, 0x90, 0x5a, 0xc1, 0xa7, 0x84, 0x39, 0x03, 0xad, 0x55, 0x02,
	0xde, 0x81, 0x0d, 0x8f, 0x64, 0x09, 0x67, 0x19, 0x79, 0x2d, 0x7c, 0x31, 0xcf, 0xd0, 0x43, 0xe8,
	0x67, 0x6a, 0xa5, 0xee, 0x34, 0xf4, 0x8c, 0x84, 0x5f, 0xc2, 0xdd, 0x23, 0x22, 0x4e, 0x69, 0x30,
	0x25, 0xa9, 0x47, 0x7e, 0x98, 0x93, 0x4c, 0x65, 0x20, 0x98, 0xa7, 0x29, 0x61, 0xc1, 0xa5, 0xb1,
	0x2e, 0x64, 0x79, 0x8f, 0x24, 0xa5, 0x01, 0x65, 0x91, 0xb9, 0x7f, 0x2e, 0xe2, 0xbf, 0x2d, 0xb8,
	0x57, 0x71, 0xa5, 0x4f, 0x47, 0x08, 0x7a, 0x32, 0x07, 0xca, 0x8f, 0xed, 0xa9, 0xb5, 0xd4, 0x9d,
	0xd3, 0xe8, 0x5c, 0x39, 0xb0, 0x3d, 0xb5, 0x96, 0x59, 0x88, 0xf9, 0x8f, 0x2a, 0x6d, 0xb6, 0x27,
	0x97, 0x32, 0xe2, 0x0b, 0x1e, 0xcf, 0x67, 0x44, 0x25, 0xcc, 0xf6, 0x8c, 0x84, 0x3e, 0x87, 0xa1,
	0xa4, 0x6f, 0xcc, 0x13, 0xc2, 0x54, 0xd6, 0x56, 0xf7, 0xdd, 0x91, 0x26, 0x78, 0x94, 0x13, 0x3c,
	0x3a, 0xcd, 0x09, 0xf6, 0x06, 0xd2, 0xf8, 0x38, 0x21, 0x0c, 0x3d, 0x03, 0x50, 0xc0, 0x20, 0xe6,
	0x99, 0xce, 0xed, 0x72, 0xa4, 0x3a, 0xe6, 0x50, 0x1a, 0xe3, 0xaf, 0xe0, 0xed, 0x23, 0x22, 0x8e,
	0xd3, 0x90, 0xa4, 0x07, 0x9c, 0x4f, 0xff, 0x5b, 0xa2, 0x4e, 0x61, 0xa3, 0xf0, 0xf4, 0x82, 0x89,
	0xf4, 0x52, 0x11, 0x9e, 0xd2, 0x80, 0x98, 0x2c, 0x69, 0x41, 0x26, 0xc0, 0x9f, 0xf1, 0x39, 0x13,
	0x26, 0x51, 0x46, 0xd2, 0x94, 0x0b, 0x3f, 0x36, 0xc9, 0xd2, 0x02, 0xfe, 0xc5, 0x82, 0xfb, 0xf5,
	0x18, 0x0d, 0x03, 0xcf, 0xa0, 0xe7, 0x67, 0x53, 0xc9, 0x7b, 0x77, 0x67, 0x75, 0x7f, 0x7b, 0x74,
	0xed, 0x17, 0x19, 0xd5, 0x23, 0xf2, 0x14, 0x44, 0x42, 0x27, 0x34, 0xcc, 0x9c, 0xce, 0xad, 0xa0,
	0x12, 0x82, 0xf7, 0xd4, 0x63, 0x38, 0xf0, 0x63, 0x9f, 0x05, 0xa4, 0x45, 0xbe, 0xf0, 0x29, 0xa0,
	0x2a, 0xc0, 0x04, 0xef, 0xc0, 0xca, 0x44, 0xab, 0x4c, 0x6e, 0x72, 0x11, 0x6d, 0xc1, 0x7a, 0x48,
	0x02, 0x3a, 0xf3, 0xe3, 0x24, 0xf6, 0x03, 0x92, 0x99, 0x24, 0xd5, 0x95, 0x78, 0x5f, 0x27, 0x25,
	0x21, 0x4c, 0x45, 0x99, 0xb5, 0x89, 0xe4, 0xaf, 0x0e, 0x6c, 0x14, 0x08, 0x4d, 0xd0, 0x06, 0x74,
	0x68, 0x68, 0x0c, 0x3b, 0x34, 0xac, 0xc1, 0x3b, 0xcd, 0xc4, 0x77, 0x6b, 0xc4, 0xa3, 0xc7, 0xf0,
	0x96, 0xa6, 0x70, 0x5c, 0x80, 0xf5, 0xd3, 0xde, 0xd0, 0xea, 0xc3, 0xdc, 0xc5, 0x73, 0x78, 0x77,
	0xc1, 0x70, 0x9c, 0xca, 0xef, 0xce, 0xa4, 0x53, 0x5b, 0x41, 0xde, 0xa9, 0x43, 0xbc, 0x7c, 0x1b,
	0x6d, 0x83, 0xf1, 0x36, 0xce, 0xa3, 0xe8, 0xeb, 0xc4, 0x68, 0xed, 0x89, 0x89, 0xe5, 0x29, 0x38,
	0x75, 0xb3, 0xca, 0x09, 0x2b, 0x0a, 0xf0, 0xb0, 0x06, 0x28, 0x0f, 0x78, 0x0f, 0x86, 0xea, 0x7d,
	0x8e, 0x27, 0x34, 0x54, 0x55, 0xc7, 0xf6, 0x06, 0x4a, 0x71, 0x40, 0xc3, 0x72, 0xd3, 0xcf, 0xa6,
	0xce, 0xb0, 0xb2, 0xf9, 0x45, 0x36, 0xc5, 0xdf, 0xc1, 0x83, 0x05, 0x32, 0x0c, 0xcb, 0x2f, 0x00,
	0xe4, 0x6f, 0xe6, 0x4a, 0x7b, 0xd3, 0x43, 0xad, 0x31, 0xe3, 0x55, 0x80, 0x78, 0x0b, 0xd0, 0xa1,
	0x7c, 0x1b, 0xb1, 0xda, 0xcf, 0xa9, 0xce, 0xb9, 0xeb, 0x6a, 0xee, 0xf0, 0xef, 0x16, 0xdc, 0x3b,
	0x91, 0xaf, 0xa3, 0x66, 0xf5, 0xaf, 0xbe, 0xf2, 0x75, 0x8c, 0x76, 0xaf, 0x65, 0xf4, 0x2a, 0x2b,
	0xbd, 0x6b, 0x58, 0xc1, 0xcf, 0x61, 0x53, 0x96, 0xd0, 0xd4, 0x67, 0x99, 0x1f, 0x08, 0xca, 0xd9,
	0x4b, 0x9a, 0x09, 0x9e, 0x5e, 0xb6, 0x79, 0xb6, 0xbf, 0x5a, 0xb0, 0x5a, 0x41, 0xa2, 0xa7, 0xba,
	0x4e, 0xaa, 0x5a, 0xa6, 0x8c, 0x5b, 0x54, 0x3b, 0xb5, 0x5c, 0xfa, 0xba, 0xcb, 0xa2, 0xd4, 0xad,
	0x15, 0x25, 0x04, 0x3d, 0xc6, 0x05, 0x31, 0xcd, 0x4d, 0xad, 0x71, 0x04, 0xef, 0x37, 0xdc, 0xc6,
	0xf0, 0xfe, 0x25, 0xac, 0x89, 0x72, 0x37, 0x67, 0x1e, 0x37, 0x30, 0x5f, 0x71, 0xe4, 0xd5, 0x70,
	0x98, 0xa8, 0x62, 0xd3, 0x3e, 0x57, 0x4b, 0x18, 0x75, 0x61, 0x40, 0x99, 0x20, 0xe9, 0x45, 0x51,
	0x5f, 0x0b, 0x19, 0xff, 0x61, 0xa9, 0x1a, 0xb5, 0x78, 0x8b, 0xb2, 0x51, 0x59, 0xb5, 0x46, 0xb5,
	0x59, 0x25, 0x40, 0x57, 0xa7, 0x4a, 0x92, 0xaf, 0x36, 0xbc, 0xbc, 0x2d, 0xf6, 0x2a, 0x6d, 0x11,
	0x41, 0xaf, 0xe8, 0x73, 0xb6, 0xa7, 0xd6, 0xb2, 0xfe, 0x97, 0x2d, 0xcc, 0xf6, 0xb4, 0x80, 0xb7,
	0x60, 0xed, 0x15, 0x8f, 0x28, 0xcb, 0xaf, 0x5f, 0x8c, 0x0b, 0x56, 0x65, 0x5c, 0xc0, 0xdb, 0xb0,
	0xfe, 0x8a, 0x47, 0x7c, 0x2e, 0x2a, 0x66, 0x7a, 0x7e, 0xb0, 0xaa, 0xf3, 0xc3, 0xae, 0x4a, 0xe8,
	0x49, 0xca, 0xcf, 0x68, 0x4c, 0x96, 0x9a, 0xee, 0xff, 0x06, 0xb0, 0x76, 0x7c, 0x7a, 0x72, 0x74,
	0x7c, 0xa0, 0x69, 0x42, 0x6f, 0xc0, 0x56, 0x81, 0xa0, 0x8f, 0x1a, 0x78, 0xac, 0x86, 0xe9, 0x36,
	0x7d, 0xf3, 0xfa, 0xf8, 0x82, 0xef, 0xa0, 0x6f, 0xa0, 0xaf, 0x23, 0x47, 0x5b, 0xcd, 0x7e, 0xcb,
	0x8b, 0xb5, 0x77, 0xfc, 0x2d, 0xac, 0xbf, 0x49, 0x42, 0x5f, 0x10, 0x73, 0x5d, 0xf4, 0x41, 0x03,
	0xd2, 0x0c, 0x88, 0xed, 0x3d, 0x7f, 0x0d, 0xfd, 0xd7, 0x34, 0x62, 0xf3, 0xe4, 0xff, 0x73, 0xf9,
	0x3d, 0x0c, 0x8b, 0x19, 0x0b, 0x3d, 0x6e, 0x40, 0x2d, 0x0e, 0x74, 0xee, 0xce, 0xcd, 0x86, 0xfa,
	0x1c, 0x7c, 0x07, 0x51, 0x58, 0xab, 0x8e, 0x11, 0xe8, 0xe3, 0x66, 0xec, 0xe2, 0x3c, 0xe4, 0x7e,
	0xd2, 0xca, 0xb6, 0x38, 0x2a, 0x00, 0x28, 0x5b, 0x3e, 0x5a, 0x12, 0x64, 0x7d, 0x8c, 0x70, 0x77,
	0x5b, 0x58, 0x16, 0x87, 0xf8, 0xb0, 0x5a, 0x69, 0x0a, 0xa8, 0x09, 0x7b, 0xb5, 0x71, 0xb4, 0x27,
	0x25, 0x86, 0xf5, 0x5a, 0x5f, 0x43, 0xcb, 0xf2, 0xb0, 0x38, 0x8a, 0xb8, 0x9f, 0xb6, 0x33, 0x2e,
	0x2e, 0x34, 0x06, 0x28, 0xdb, 0x57, 0x63, 0xd6, 0xae, 0x74, 0xb8, 0xdb, 0x7c, 0x08, 0x28, 0x3f,
	0xff, 0x32, 0x5a, 0xea, 0xf5, 0xc1, 0xbd, 0xe1, 0x91, 0xe3, 0x3b, 0xe8, 0x67, 0x4b, 0x4d, 0x00,
	0x57, 0x3b, 0x02, 0x7a, 0xb2, 0xe4, 0x85, 0x36, 0x75, 0x43, 0xf7, 0xb3, 0xdb, 0x81, 0x16, 0xde,
	0x5d, 0x7e, 0xf4, 0x92, 0x0b, 0x2e, 0x9c, 0xb7, 0xdb, 0xc2, 0x32, 0x3f, 0x64, 0xd2, 0x57, 0x3d,
	0xf6, 0xc9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x0d, 0xf9, 0xf5, 0xa2, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OTPGOBackendClient is the client API for OTPGOBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OTPGOBackendClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	UpdateProfile(ctx context.Context, in *Context, opts ...grpc.CallOption) (*ResponseStatus, error)
	Signup(ctx context.Context, in *Context, opts ...grpc.CallOption) (*ResponseStatus, error)
	GetTicker(ctx context.Context, in *GetTickerRequest, opts ...grpc.CallOption) (*GetTickerResponse, error)
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	GetOpenOrders(ctx context.Context, in *GetOpenOrdersRequest, opts ...grpc.CallOption) (*GetOpenOrdersResponse, error)
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Context, error)
	GetTransactionHistory(ctx context.Context, in *GetTransactionHistoryRequest, opts ...grpc.CallOption) (*GetTransactionHistoryResponse, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type oTPGOBackendClient struct {
	cc *grpc.ClientConn
}

func NewOTPGOBackendClient(cc *grpc.ClientConn) OTPGOBackendClient {
	return &oTPGOBackendClient{cc}
}

func (c *oTPGOBackendClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) UpdateProfile(ctx context.Context, in *Context, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) Signup(ctx context.Context, in *Context, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetTicker(ctx context.Context, in *GetTickerRequest, opts ...grpc.CallOption) (*GetTickerResponse, error) {
	out := new(GetTickerResponse)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	out := new(GetOrderBookResponse)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetOrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetOpenOrders(ctx context.Context, in *GetOpenOrdersRequest, opts ...grpc.CallOption) (*GetOpenOrdersResponse, error) {
	out := new(GetOpenOrdersResponse)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetOpenOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/PlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Context, error) {
	out := new(Context)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetTransactionHistory(ctx context.Context, in *GetTransactionHistoryRequest, opts ...grpc.CallOption) (*GetTransactionHistoryResponse, error) {
	out := new(GetTransactionHistoryResponse)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetTransactionHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPGOBackendClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, "/otpgo.trading.backend.OTPGOBackend/GetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OTPGOBackendServer is the server API for OTPGOBackend service.
type OTPGOBackendServer interface {
	Login(context.Context, *LoginRequest) (*ResponseStatus, error)
	Logout(context.Context, *LogoutRequest) (*ResponseStatus, error)
	UpdateProfile(context.Context, *Context) (*ResponseStatus, error)
	Signup(context.Context, *Context) (*ResponseStatus, error)
	GetTicker(context.Context, *GetTickerRequest) (*GetTickerResponse, error)
	GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*ResponseStatus, error)
	GetOpenOrders(context.Context, *GetOpenOrdersRequest) (*GetOpenOrdersResponse, error)
	PlaceOrder(context.Context, *PlaceOrderRequest) (*ResponseStatus, error)
	GetProfile(context.Context, *GetProfileRequest) (*Context, error)
	GetTransactionHistory(context.Context, *GetTransactionHistoryRequest) (*GetTransactionHistoryResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
}

func RegisterOTPGOBackendServer(s *grpc.Server, srv OTPGOBackendServer) {
	s.RegisterService(&_OTPGOBackend_serviceDesc, srv)
}

func _OTPGOBackend_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Context)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).UpdateProfile(ctx, req.(*Context))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Context)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).Signup(ctx, req.(*Context))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetTicker(ctx, req.(*GetTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetOrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetOpenOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetOpenOrders(ctx, req.(*GetOpenOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetTransactionHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetTransactionHistory(ctx, req.(*GetTransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPGOBackend_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPGOBackendServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otpgo.trading.backend.OTPGOBackend/GetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPGOBackendServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OTPGOBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "otpgo.trading.backend.OTPGOBackend",
	HandlerType: (*OTPGOBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _OTPGOBackend_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _OTPGOBackend_Logout_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _OTPGOBackend_UpdateProfile_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _OTPGOBackend_Signup_Handler,
		},
		{
			MethodName: "GetTicker",
			Handler:    _OTPGOBackend_GetTicker_Handler,
		},
		{
			MethodName: "GetOrderBook",
			Handler:    _OTPGOBackend_GetOrderBook_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _OTPGOBackend_GetBalance_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OTPGOBackend_CancelOrder_Handler,
		},
		{
			MethodName: "GetOpenOrders",
			Handler:    _OTPGOBackend_GetOpenOrders_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _OTPGOBackend_PlaceOrder_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _OTPGOBackend_GetProfile_Handler,
		},
		{
			MethodName: "GetTransactionHistory",
			Handler:    _OTPGOBackend_GetTransactionHistory_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _OTPGOBackend_GetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
